<template>
       <div class="footer">
            <p>Author: Camryn Tang | <a href="mailto:camrynt2468@gmail.com">camrynt2468@gmail.com</a></p>
        </div>
</template>

<style scoped>
footer {
    text-align: center;
    padding: 15px; 
    background: rgba(0, 0, 0, 0.8); 
    border-radius: 10px; 
    margin-top: 10px; 
    box-shadow: 0 -4px 10px rgba(0, 0, 0, 0.5); 
    position: absolute; 
    bottom: 20px; 
    white-space: nowrap; 
}

.footer p {
    display: inline; 
}</style>

